require("config")
require("config.lazy")
require("scripts")
require("lazy").setup("plugins")

vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set showcmd")
vim.cmd("set clipboard=unnamedplus")

vim.cmd("highlight Normal guibg=NONE ctermbg=NONE")
