vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
-- Split Panes keymap --
vim.keymap.set("n", "<A-h>", "<C-w>h")
vim.keymap.set("n", "<A-j>", "<C-w>j")
vim.keymap.set("n", "<A-k>", "<C-w>k")
vim.keymap.set("n", "<A-l>", "<C-w>l")
vim.keymap.set("n", "<A-x>", ":split<CR><C-w>j", { silent = true })
vim.keymap.set("n", "<A-v>", "<C-w>v<C-w>l")
vim.keymap.set("n", "<A-c>", "<C-w>c")
vim.keymap.set("n", "<A-f>", ":Neotree filesystem reveal left toggle=true<CR>", { silent = true })
vim.keymap.set("n", "<leader>ss", ":Neotree source=symbols reveal left toggle=true<CR>", { silent = true })
vim.keymap.set("n", "<leader>sg", ":Neotree source=git reveal left toggle=true<CR>", { silent = true })
